package gov.ornl.csed.cda.Falcon;

/**
 * Created by csg on 8/18/16.
 */
public class FalconViewTemplateKeys {
    // VARIABLE NAMES
    public static final String VARIABLES = "VARIABLES";

    // GENERAL DISPLAY SETTINGS
    public static final String GENERAL_HISTOGRAM_BIN_COUNT = "GENERAL_HISTOGRAM_BIN_COUNT";
    public static final String GENERAL_VARIABLE_PANEL_HEIGHT = "GENERAL_VARIABLE_PANEL_HEIGHT";
    public static final String GENERAL_SHOW_BUTTONS_CHECKBOX = "GENERAL_SHOW_BUTTONS_CHECKBOX";

    // TIME SERIES DISPLAY SETTINGS
    public static final String TIME_SERIES_PLOT_UNIT_WIDTH = "TIME_SERIES_PLOT_UNIT_WIDTH";
    public static final String TIME_SERIES_DETAIL_PLOT_DISPLAY_OPTION  = "TIME_SERIES_DETAIL_PLOT_DISPLAY_OPTION";
    public static final String TIME_SERIES_PLOT_CHRONO_UNIT = "TIME_SERIES_PLOT_CHRONO_UNIT";
    public static final String TIME_SERIES_MOVING_RANGE_DISPLAY = "TIME_SERIES_MOVING_RANGE_DISPLAY";
    public static final String TIME_SERIES_SYNC_TIME_SERIES_SCROLL_BARS = "TIME_SERIES_SYNC_TIME_SERIES_SCROLL_BARS";
    public static final String TIME_SERIES_POINT_COLOR = "TIME_SERIES_POINT_COLOR";
    public static final String TIME_SERIES_LINE_COLOR = "TIME_SERIES_LINE_COLOR";
    public static final String TIME_SERIES_STDDEV_RANGE_COLOR = "TIME_SERIES_STDDEV_RANGE_COLOR";
    public static final String TIME_SERIES_MINMAX_RANGE_COLOR = "TIME_SERIES_MINMAX_RANGE_COLOR";
    public static final String TIME_SERIES_SPECTRUM_POSITIVE_COLOR = "TIME_SERIES_SPECTRUM_POSITIVE_COLOR";
    public static final String TIME_SERIES_SPECTRUM_NEGATIVE_COLOR = "TIME_SERIES_SPECTRUM_NEGATIVE_COLOR";

    // SELECTION DETAILS DISPLAY SETTINGS
    public static final String SELECTION_DETAILS_PLOT_HEIGHT = "SELECTION_DETAILS_PLOT_HEIGHT";
    public static final String SELECTION_DETAILS_BIN_COUNT = "SELECTION_DETAILS_BIN_COUNT";
}
